services:
  bot:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    command: ["python", "bot.py"]

  db:
    env_file:
      - .env
    image: postgres:15-alpine
    ports:
      - 5430:5432
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
